name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    services:
      # Label used to access the service container
      redis:
        image: docker.dragonflydb.io/dragonflydb/dragonfly
        ports:
          - 6389:6379
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: ^10.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm tsc
      - name: Run tests
        run: pnpm test
